name: Android CI

on:
  push:
    branches: [ "beta" ]
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/**"
      - ".idea/"
      - "fastlane/"
      - '.gitignore'
      - "*.md"
      - "LICENSE"
  pull_request:
    branches: [ "beta" ]
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/**"
      - ".idea/"
      - "fastlane/"
      - '.gitignore'
      - "*.md"
      - "LICENSE"
  workflow_dispatch:

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Create Sign File
        run: |
          echo releaseType=CI >> package.properties
          echo "${{ secrets.KEYSTORE_SECRET }}" | base64 -d > key.jks
          echo "AKANE_RELEASE_STORE_FILE=${{ github.workspace }}/key.jks" >> package.properties
          echo "AKANE_RELEASE_STORE_PASSWORD=${{ secrets.KEYSTORE_PWD }}" >> package.properties
          echo "AKANE_RELEASE_KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> package.properties
          echo "AKANE_RELEASE_KEY_PASSWORD=${{ secrets.KEY_PWD }}" >> package.properties

      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Find Apk
        run: |
          echo "APK_FILE=$(find app/build/outputs/apk/release -name '*.apk')" >> $GITHUB_ENV
          export APK_FILE=$(find app/build/outputs/apk/release -name '*.apk')
          echo "APK_FILE_NAME=$(basename $APK_FILE .apk)" >> $GITHUB_ENV

      - name: Upload Apk
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APK_FILE_NAME }}
          path: ${{ env.APK_FILE }}
          compression-level: 9
